### ISSUE TITLE
When file properties are empty, view-count is inserted in the wrong place.

### ISSUE THREAD

**Issue by ku-zhen** [trey-wallis/obsidian-view-count#1]
When file properties are empty, view-count is inserted in the wrong place. like:

![image](https://github.com/trey-wallis/obsidian-view-count/assets/61906420/4b8dad70-22c2-427b-a366-d2ee1b6d84f5)

By the way, hopefully it will exclude some folders from updating viewcount, such as template files.

Thanks.

**Comment by decaf-dev** [comment]
Hi @ku-zhen. Thanks for the feature request.

Would you mind explaining what you mean by in the wrong place? I do not understand from this screenshot.

Yes, excluded files would be good. Would it be helpful to have a setting that would allow you to exclude a list of folders? Template files as far as I understand don't have any special extension or format.

**Comment by decaf-dev** [comment]
I have decided to rework the plugin. View count is now stored in an external file instead of the `view-count` property. All files are now tracked as well. The view count will appear in the status bar.
