### ISSUE TITLE
Trending notes

### ISSUE THREAD

**Issue by decaf-dev** [trey-wallis/obsidian-view-count#13]
> Let me know if things are working

Yes now it is working fine. I have one more request. As we can know how many times we have opened any particular note with the help of this plugin. Now I want to use that data to list out the notes that are in trending this week. Means which are the top ten notes I am opening more frequently in this week. And it should be dynamically update the list. 

I have tried to achieve this using dataview query but there is no way for dataview to know which note is opened most in the past 7 days. It only listing out the most opened note of all time by looking at the view-count property field value. 

So is there a way we can tell dataview that these are the notes we have opened the most in past 7 days or past 30 days.

_Originally posted by @Gourav1910 in https://github.com/trey-wallis/obsidian-view-count/issues/10#issuecomment-2083560399_

**Comment by decaf-dev** [comment]
@gourav1910 that information is not currently stored in property storage or the file storage. Only the total view count and the last view date is stored. This would require saving the time for every view. I don't think that is practical for storing in frontmatter, as it would take up a lot of room. In file storage though, it is feasible.

**Comment by Gourav1910** [comment]
> @Gourav1910 that information is not currently stored in property storage or the file storage. Only the total view count and the last view date is stored. This would require saving the time for every view. I don't think that is practical for storing in frontmatter, as it would take up a lot of room. In file storage though, it is feasible.

I was thinking about a solution. Although I am not a coder so I don't know how hard it would be to implement or whether it is the best solution or not. So I was thinking about a property field such as "view-day-DD". Here DD is the date value of the current month. Now just like view-count field storing data of all time this property will store the data of any note for that day by adding the number of times we have opened it. Then for the next day it will again create the next day field. Such as view-day-01, view-day-02, etc. So it is storing the value in similar way of view-count but just time frame is limited to particular day. Then next month it will delete all the previous data and add new data of that month. So it will store one month of data only. But we want to query it also which I can't getting how to do which dynamically pick last seven or whatever days value. 

This is just a random idea. But I think you better know what should be done.

**Comment by RikardSwed** [comment]
This sounds like a nice feature. However in the meantime you might want to use the plugin called recent files which sort of gives you this feature

**Comment by Gourav1910** [comment]
> This sounds like a nice feature. However in the meantime you might want to use the plugin called recent files which sort of gives you this feature

Yes I am also using that plugin. But my idea is to list out the notes on top on which I am actively or aggressively working on this week. The word trending indicate that. It would also help us understand at a glance that what is currently going on in our consciousness. We are inclined towards which ideas or work. It tells a story that in what rhythm of life we are in. But yeah recent files plugin is also very useful.

**Comment by decaf-dev** [comment]
@Gourav1910 I just added the support structure in 2.0.0 to be able to implement trending notes in the next update. Do you use Dataview or DataviewJS? Dataview pulls from frontmatter but DataviewJS can pull from plugin data.

**Comment by Gourav1910** [comment]
> @Gourav1910 I just added the support structure in 2.0.0 to be able to implement trending notes in the next update. Do you use Dataview or DataviewJS? Dataview pulls from frontmatter but DataviewJS can pull from plugin data.

Hey, thankyou so much for your work🙌. Currently I am using dataview query only. As I don't know coding so dataview is easy for me. But if you implement it for dataviewjs then you can provide the query which I can copy and paste. Again thanks 👍😊.

**Comment by decaf-dev** [comment]
@Gourav1910 Alrighty. I have implemented trending notes in 2.2.0. Please read the entire README for instructions on how to get started. Let me know if you have any issues. Thanks!
