### ISSUE TITLE
Increase delay time

### ISSUE THREAD

**Issue by np6390** [trey-wallis/obsidian-view-count#30]
Hi, great plugin btw, but max 5 seconds is a bit short for some use case, 

Like then I just search for something and look by, but don't want it to be increase the view-count.

Or many when I create a new note, it quickly add the view-count before I got my template be ready, so can it like increase to 1 minutes? even 5 minute for like document if I have read through it, then the view-count will be increase.

**Comment by decaf-dev** [comment]
Hi @np6390. The delay is just for people that use the templater plugin to insert a template. If you are working on creating a template in a note and the view count is being inserted, that is a different situation. For that case, I would recommend making a `templates` folder and added it to the `Excluded Paths` in the settings.

**Comment by decaf-dev** [comment]
For reading a document, I could see it as annoying if you would like the view count only to be incremented when you finish, however that seems like a niche case for the general users of this plugin. For that case, I would recommend not using this plugin and just making a button that you can click to increment the view count.
