### ISSUE TITLE
FR: Turn off automatic View Count To New Notes

### ISSUE THREAD

**Issue by brimwats** [trey-wallis/obsidian-view-count#44]
The Templater delay is nowhere long enough for me and it's becoming a real pain. If I could I'd set at at 10 or 200000, but more ideally I'd just like to disable the automatic addition of view count to all new notes because all of my templates have view-count: 1 in them. This is a FR for a toggle to disable the addition of view-count to new notes

**Comment by decaf-dev** [comment]
Hi @brimwats. It seems like Templater is pretty slow in some vaults.

So it seems like you want your notes to have their `view-count` property updated (if that property exists), but you do NOT want the plugin to add a `view-count` property to any new note that is created?

**Comment by brimwats** [comment]
> it seems like you want your notes to have their view-count property updated (if that property exists), but you do NOT want the plugin to add a view-count property to any new note that is created?

precisely!! thank you 😊 

my vault is over 10k md files for the reference (and several other types)

**Comment by decaf-dev** [comment]
Added in 2.5.0. Please enable `Sync view count` and `Skip new notes`. This will give you the behavior that you described.

**Comment by brimwats** [comment]
Thank you so much for your labour!!

**Comment by brimwats** [comment]
Small UI suggestion: perhaps toggling Skip new notes should hide the templater delay selection? Can see people getting confused that the two might conflict
