### ISSUE TITLE
FR: Exclude certain paths

### ISSUE THREAD

**Issue by brimwats** [trey-wallis/obsidian-view-count#8]
I would really like to exclude this plugin from incrementing the weekly notes, as that interferes with templates for those weekly notes. Could we have a path exclusion option?

**Comment by decaf-dev** [comment]
That makes sense. Are you using "Property" storage? I will add this feature

**Comment by brimwats** [comment]
Yes I am! thank you so much!

**Comment by decaf-dev** [comment]
Added in 1.2.0
